package Project;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author ra21554517
 */
public class MainView extends javax.swing.JFrame {
    Conversor cv = new Conversor();
    CorretorConversor cc = new CorretorConversor();
    ArrayList linhas = new ArrayList();
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setVisible(true);
    }

    public String getTextoGerado() {
        return textoGerado.getText();
    }

    public void setTextoGerado(String textoGerado) {
        this.textoGerado.setText(textoGerado);
    }

    public String getTextoOriginal() {
        return textoOriginal.getText();
    }

    public void setTextoOriginal(String textoGerado) {
        this.textoOriginal.setText(textoGerado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoOriginal = new javax.swing.JTextArea();
        botãoGerador = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoGerado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Digite seu código:");

        textoOriginal.setColumns(20);
        textoOriginal.setForeground(new java.awt.Color(51, 51, 255));
        textoOriginal.setRows(5);
        jScrollPane1.setViewportView(textoOriginal);

        botãoGerador.setText("Gerar código em C");
        botãoGerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoGeradorActionPerformed(evt);
            }
        });

        textoGerado.setColumns(20);
        textoGerado.setForeground(new java.awt.Color(204, 0, 51));
        textoGerado.setRows(5);
        jScrollPane2.setViewportView(textoGerado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(botãoGerador)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botãoGerador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botãoGeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoGeradorActionPerformed
        // TODO add your handling code here:
        linhas = cv.textBreaker(getTextoOriginal());
        setTextoGerado(cc.correctText(linhas));
    }//GEN-LAST:event_botãoGeradorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botãoGerador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textoGerado;
    private javax.swing.JTextArea textoOriginal;
    // End of variables declaration//GEN-END:variables
}
